### ISSUE TITLE
Problem computing SVD

### ISSUE THREAD

**Issue by joreynajr** [bnaras/PMA#2]
Hi, I am just testing out this package with a dataset where I have 40 samples and 17654 features. I just want to reproduce similar results from figure 3 of the paper using my own dataset by splitting my features into a left half and a right half so I'll have a left matrix (40 x 8827) and a right matrix (40 x 8827). The idea is that these features will correlate very well with one another and therefore I should be able to produce something like figure 3 however, SVD fails to run and the error message is very vague, how would you suggest solving this? I'm pasting a sample code without the data but let me know if you need it.

Many thanks,

Joaquin

Code:
<pre>
left_idx = ceiling(ncol(full_rnaseq)/ 2)
left_rna = full_rnaseq[,1:left_idx] # dim = 40 x 8827
right_rna = full_rnaseq[, left_idx:ncol(full_rnaseq)] # dim = 40 x 8827
perm.out <- CCA.permute(left_rna,
                        right_rna,
                        typex="standard",
                        typez="standard",
                        nperms=7)
</pre>

**Comment by bnaras** [comment]
Need a reprex to say anything useful.

**Comment by joreynajr** [comment]
I solved my issue, I believe I just forgot to remove a character column. Closing this issue, thanks for the reply. 

Joaquin
